# Generated by Django 6.0.1 on 2026-02-19 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, unique=True)),
                ('parts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='customer_csvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80, unique=True)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeeprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TEPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=60)),
                ('tep_code', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_codes', to='app.customer')),
            ],
            options={
                'unique_together': {('customer', 'part_code', 'tep_code')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_partcode', models.CharField(max_length=80)),
                ('mat_partname', models.CharField(max_length=160)),
                ('mat_maker', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('pc', 'pc'), ('pcs', 'pcs'), ('m', 'm'), ('g', 'g'), ('kg', 'kg')], max_length=10)),
                ('dim_qty', models.FloatField()),
                ('loss_percent', models.FloatField(default=10.0)),
                ('total', models.FloatField()),
                ('tep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='app.tepcode')),
            ],
        ),
    ]
